import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import "@/app/globals.css";
import React from "react";
import { getMessages } from "next-intl/server";
import Header from "@/app/ui/Header";
import { ThemeProvider } from "@mui/material/styles";
import { myTheme } from "@/app/theme";
import styles from "@/app/rootlayout.module.css";

type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { locale } = params;
  const messages = await getMessages();
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={myTheme}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            <main className={styles.main}>{children}</main>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
